class Subasta:
    id = ""
    subastador = ""
    lugar = ""
    expediente = ""
    fechaFin = ""
    horaFin = ""
    estado = ""
    tipoFinca = ""
    url = ""
    ubicacion = ""
    marcadoBorrar = "false"
